//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Personeller1 = new HashSet<Personeller>();
        }
    
        public int PersonelID { get; set; }
        [Required(ErrorMessage ="Ad alaný gereklidir.")]
        public string Ad { get; set; }
        [Required(ErrorMessage = "Soyad alaný gereklidir.")]
        public string Soyad { get; set; }
        [Required(ErrorMessage ="Telefon alaný gereklidir.")]
        public string Telefon { get; set; }
        [Display(Name = "Yöneticisi")]
        public Nullable<int> YoneticiID { get; set; }
        [Required(ErrorMessage = "Depatman alaný gereklidir.")]
        [Display(Name = "Departman Adý")]
        public int DepartmanID { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personeller> Personeller1 { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Yöneticisi")]
        public virtual Personeller Personeller2 { get; set; }
    }
}
